### ISSUE TITLE
How can I change font size in tooltip?

### ISSUE THREAD

**Issue by x1a0** [Bahnzo/POE-ItemInfo#37]
I did try change the `font size` in config.ini but nothing changed...

**Comment by Bahnzo** [comment]
You have to right-click on the icon in the tray (while it's running) and choose settings.

**Comment by x1a0** [comment]
@Bahnzo Hey thanks for replying. But unfortunately, still not working... in the settings window it says font size is 20 now, but it's not larger than default in tooltip... (default is 11 or 10 i think).

**Comment by Bahnzo** [comment]
A couple things then. First, make sure you are restarting the script after making changes in the settings. They only take effect after a restart of the script (it's an option in the right click menu also). I forget to do this often.  

If that doesn't work, then it's something on your end. I have to change the font size each update (I like it smaller) so I'm positive it's working. I'm not sure what would cause it however.

**Comment by x1a0** [comment]
Still no luck with more tries. But obviously changing Window's font size settings helps there. Anyway, thanks for the GREAT tool!

**Comment by XiMMiX** [comment]
Are you by any chance compiling the script? 
If so, could you check if running the non-compiled POE-ItemInfo.ahk fixes your problem? Or alternatively renaming your compiled file to "autohotkey.exe".
