### ISSUE TITLE
Crit rebalance in 2.2

### ISSUE THREAD

**Issue by XiMMiX** [Bahnzo/POE-ItemInfo#44]
Ascendancy (2.2) introduced changes to crit multi on jewels/uniques and master crafted crit chance on amulets. We'll get (already have?) the changes to uniques using PoE-Scrapy once changed on the wiki. But the other changes to mods we'll have to manually change.

Details:
https://www.pathofexile.com/forum/view-thread/1596094

**Comment by Bahnzo** [comment]
I rewrote PoE-Scrappy, updating it to Python3 and using Beautiful soup.
It's much easier to read now and I commented it so future people will be
able to understand it easier. It's available in my github. I need to update
it...I added threading to it just the learn that.

**Comment by XiMMiX** [comment]
I saw you cloned PoE-Scrapy and updated Unqiues.txt so I assumed you used PoE-Scrapy. 
I'lll use scape_poe_uniques from now on.

About the crit changes, I've looked at it a bit more and there seem to be less changes than I initially thought. So I think I'll be able to commit an update later today.
