### ISSUE TITLE
Indiviually priced items

### ISSUE THREAD

**Issue by XiMMiX** [Bahnzo/POE-ItemInfo#45]
Individually priced, rare items (or those with a note) in public stash tabs don't display correctly. Their affixes don't show in the tooltip.

**Comment by Bahnzo** [comment]
Ahhh. I'm guessing since they have that extra info from the clipboard which
the script doesn't recognize, it's causing an error.

**Comment by Bahnzo** [comment]
Fixed. Made a change in how the info was copied from the clipboard. Omits lines that contain "Note:" in them.
