### ISSUE TITLE
Map bugs

### ISSUE THREAD

**Issue by XiMMiX** [Bahnzo/POE-ItemInfo#46]
Maps seem bugged in 2 ways, possibly related:
1. Some maps show affix counts.
2. Some maps don't show as maps at all, but a a normal item with itemlvl and max_sockets display.

I've checked and 2.0.9 also has these errors so the problem wasn't introduced by the fix for #45 as I first suspected.

**Comment by XiMMiX** [comment]
Uploaded some map data to reproduce this problem later (I'll be running at least some of these maps).

[corrupted-rare-desert_shows-affix-count.txt](https://github.com/Bahnzo/POE-ItemInfo/files/183096/corrupted-rare-desert_shows-affix-count.txt)
[corrupted-rare-museum_ok.txt](https://github.com/Bahnzo/POE-ItemInfo/files/183098/corrupted-rare-museum_ok.txt)
[corrupted-rare-tropicalisland_ok.txt](https://github.com/Bahnzo/POE-ItemInfo/files/183099/corrupted-rare-tropicalisland_ok.txt)
[corrupted-rare-vaal-pyramid_shows-affix-count.txt](https://github.com/Bahnzo/POE-ItemInfo/files/183097/corrupted-rare-vaal-pyramid_shows-affix-count.txt)
[rare_necropolis-not_recognized_as_map.txt](https://github.com/Bahnzo/POE-ItemInfo/files/183100/rare_necropolis-not_recognized_as_map.txt)

**Comment by Bahnzo** [comment]
Do none of these maps show correctly? (I have to admit, I never look at maps any more)

They are all corrupted as well.

**Comment by XiMMiX** [comment]
The files with names that end with "_ok" display correctly. The other ones don't, the part after "_" describes the problem.

I don't think the problem is related to them being corrupted. The problem isn't limited to corrupted maps.

In case you don't know: If you turn off the "only show tooltip if PoE is frontmost" option you can ctrl+c the text from the textfiles and check for yourself.

**Comment by Bahnzo** [comment]
Ok, so I see what you mean about the affix count. The necro map shows fine though. I also noticed some rare maps of mine show the affix problem w/o being corrupted so that's certainly not the issue. I'll check into it further with a debugger this weekend and see what I can dig up.

**Comment by Bahnzo** [comment]
Fixed. Issue was some maps had text that triggered the script thinking they were affixes. Example: "Monsters have 300% increased critical strike chance" triggered finding critical strike chance. Solution was to exclude maps from being scanned for affixes.
