### ISSUE TITLE
Wrong affix range of hybrid defences and stun recovery

### ISSUE THREAD

**Issue by EndlessCheng** [Bahnzo/POE-ItemInfo#54]
![](https://cloud.githubusercontent.com/assets/7086966/15490823/ffdd46d0-219d-11e6-80af-77c9473c4928.png)
According to the [wiki](http://pathofexile.gamepedia.com/Item_affix#Hybrid_Defences_and_Stun_Recovery),
the affix (15% increased Evasion and Energy Shield) of the item should have range between 15 to 23.

```
Rarity: Rare
Torment Hold
Assassin's Mitts
--------
Evasion Rating: 105 (augmented)
Energy Shield: 31 (augmented)
--------
Requirements:
Level: 58
Dex: 45
Int: 45
--------
Sockets: G 
--------
Item Level: 58
--------
+28 to Intelligence
Adds 1-22 Lightning Damage to Attacks
15% increased Evasion and Energy Shield
+88 to maximum Life
8% increased Stun Recovery
```

**Comment by Bahnzo** [comment]
I'm no longer updating this.
