### ISSUE TITLE
Not displaying any info since patch 2.3.2

### ISSUE THREAD

**Issue by tbarusseau** [Bahnzo/POE-ItemInfo#55]
Hello,

Since 07/20/16 2.3.2 patch, PoE-ItemInfo fails to display any info on newly dropped items
I asked around on reddit and it looks like I'm not the only one.
Can you take a look at it?

Thanks in advance.

Edit : it looks like this is because of a newly added tag inside of a copied item. [When dropped in a map, the item will display "Map Drop".](http://image.prntscr.com/image/e9d12badcd10485482715bb91530c03e.png)

And [here is a temporary fix by /u/windows149](http://i.imgur.com/7WCUfTz.jpg)

**Comment by kylezwarich** [comment]
Hi,

This version is no longer being updated. Another user has taken over maintenance at:

https://github.com/aRTy42/POE-ItemInfo/releases 

The POE Forum thread is here:

https://www.pathofexile.com/forum/view-thread/1678678

**Comment by tbarusseau** [comment]
Closing issue.
