### ISSUE TITLE
Elemental dps calculation wrong

### ISSUE THREAD

**Issue by mogwai316** [Bahnzo/POE-ItemInfo#56]
Tried using this today, but it is not calculating dps of elemental weapons correctly.  For example, Hyaon's Fury it shows as 1.3 elemental dps when it should be 360+.  Also, a rapier with 48-98 fire, 7-134 lightning at 1.75 aps is shown as 96.3 edps when it should be 251.1.

**Comment by kylezwarich** [comment]
Hi,

This version is no longer being updated. Another user has taken over maintenance at:

https://github.com/aRTy42/POE-ItemInfo/releases

The POE Forum thread is here:

https://www.pathofexile.com/forum/view-thread/1678678

**Comment by mogwai316** [comment]
Thanks, that version is working better!
